// GitHub API client + analysis.
// With a connected user token, requests go straight from the browser.
// Without one, they fall back to a server-side proxy that uses the app
// owner's GITHUB_TOKEN (never exposed to the client).

import { fetchGitHubProxy } from "@/lib/api/github.functions";

const GH = "https://api.github.com";

export type WeekPoint = {
  weekIdx: number;
  date: string;
  label: string;
  additions: number;
  deletions: number;
  net: number;
  cumulative: number;
  commits: number;
  velocity: number;
};

export type CommitRow = {
  sha: string;
  shortSha: string;
  author: string;
  authorLogin: string | null;
  avatar: string | null;
  date: string;
  message: string;
  firstLine: string;
  additions: number;
  deletions: number;
  total: number;
  files: number;
  aiSignals: string[];
  url: string;
};

export type LanguageSlice = { name: string; bytes: number; pct: number };
export type Contributor = {
  login: string;
  avatar: string;
  commits: number;
  additions: number;
  deletions: number;
};

export type Analysis = {
  owner: string;
  repo: string;
  fullName: string;
  url: string;
  description: string | null;
  stars: number;
  forks: number;
  openIssues: number;
  watchers: number;
  defaultBranch: string;
  createdAt: string;
  updatedAt: string;
  primaryLanguage: string | null;
  series: WeekPoint[];
  totalCommitsYear: number;
  totalAdditionsYear: number;
  totalDeletionsYear: number;
  netLocYear: number;
  avgDailyLoc: number;
  monthlyCommitChange: number;
  largestWeek: WeekPoint | null;
  languages: LanguageSlice[];
  contributors: Contributor[];
  recentCommits: CommitRow[];
  commitsAnalyzed: number;
  avgLocPerCommit: number;
  medianLocPerCommit: number;
  aiScore: number;
  aiBreakdown: { label: string; value: number; weight: number }[];
  aiReason: string;
};

const AI_MESSAGE_PATTERNS = [
  /co-authored-by:.*(claude|copilot|chatgpt|gpt-4|cursor|lovable|gemini|aider|devin)/i,
  /\b(generated by|written by|created with)\s+(claude|copilot|chatgpt|ai|gpt|cursor|lovable|gemini)\b/i,
  /\b(claude|copilot|chatgpt|cursor|lovable|aider|devin)\b.*\b(commit|generated|added|wrote)\b/i,
  /^(feat|fix|chore|refactor)\([a-z0-9-]+\):\s+.{120,}/i, // unusually long conventional commits
];

function detectAiSignals(message: string, additions: number, files: number): string[] {
  const signals: string[] = [];
  if (/co-authored-by:.*(claude|copilot|chatgpt|cursor|lovable|gemini|aider|devin)/i.test(message))
    signals.push("AI co-author");
  if (/\b(claude|copilot|chatgpt|cursor|lovable|aider|devin|gemini)\b/i.test(message))
    signals.push("AI keyword");
  if (/generated\s+by/i.test(message)) signals.push("'generated by'");
  if (additions > 800 && files >= 5) signals.push("large batch");
  if (additions > 2000) signals.push("huge addition");
  return signals;
}

function throwGhError(status: number, rateLimited: boolean): never {
  if (status === 401) throw new Error("Invalid GitHub token. Reconnect in the GitHub panel.");
  if (status === 403)
    throw new Error(
      rateLimited
        ? "GitHub rate limit reached. Connect your GitHub account to keep going."
        : "GitHub rejected the request (403).",
    );
  if (status === 404) throw new Error("Repository or user not found.");
  if (status === 409) throw new Error("Repository is empty.");
  throw new Error(`GitHub API error: ${status}`);
}

async function ghJson(url: string, token: string | null, attempts = 5): Promise<any> {
  for (let i = 0; i < attempts; i++) {
    if (token) {
      const res = await fetch(url, {
        headers: {
          Accept: "application/vnd.github+json",
          Authorization: `Bearer ${token}`,
        },
      });
      if (res.status === 202) {
        await new Promise((r) => setTimeout(r, 1500));
        continue;
      }
      if (!res.ok) {
        throwGhError(res.status, res.headers.get("x-ratelimit-remaining") === "0");
      }
      return res.json();
    }

    // No user token — go through the server proxy (owner PAT fallback).
    const path = url.replace(GH, "");
    const { status, bodyJson, rateLimited } = await fetchGitHubProxy({ data: { path } });
    if (status === 202) {
      await new Promise((r) => setTimeout(r, 1500));
      continue;
    }
    if (status < 200 || status >= 300) throwGhError(status, rateLimited);
    return bodyJson ? JSON.parse(bodyJson) : null;
  }
  throw new Error("GitHub is still computing stats. Try again shortly.");
}

export type Viewer = { login: string; name: string | null; avatar: string };

/** Validate a token and return the authenticated user's profile. */
export async function fetchViewer(token: string): Promise<Viewer> {
  const res = await fetch(`${GH}/user`, {
    headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}` },
  });
  if (res.status === 401)
    throw new Error("That token was rejected by GitHub. Check it and try again.");
  if (!res.ok) throw new Error(`Could not verify token (${res.status}).`);
  const u = await res.json();
  return { login: u.login, name: u.name ?? null, avatar: u.avatar_url };
}

async function resolveRepo(
  input: string,
  token: string | null,
): Promise<{ owner: string; repo: string }> {
  const cleaned = input
    .trim()
    .replace(/^https?:\/\/github\.com\//, "")
    .replace(/\.git$/, "");
  if (cleaned.includes("/")) {
    const [owner, repo] = cleaned.split("/");
    return { owner, repo };
  }
  const repos = await ghJson(
    `${GH}/users/${encodeURIComponent(cleaned)}/repos?per_page=100&sort=updated`,
    token,
  );
  if (!Array.isArray(repos) || repos.length === 0)
    throw new Error("That user has no public repositories.");
  const top =
    repos
      .filter((r: any) => !r.fork)
      .sort((a: any, b: any) => b.stargazers_count - a.stargazers_count)[0] ?? repos[0];
  return { owner: top.owner.login, repo: top.name };
}

function median(arr: number[]): number {
  if (!arr.length) return 0;
  const s = [...arr].sort((a, b) => a - b);
  const m = Math.floor(s.length / 2);
  return s.length % 2 ? s[m] : Math.round((s[m - 1] + s[m]) / 2);
}

async function pool<T, R>(items: T[], size: number, fn: (t: T) => Promise<R>): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let i = 0;
  await Promise.all(
    Array.from({ length: Math.min(size, items.length) }, async () => {
      while (i < items.length) {
        const idx = i++;
        out[idx] = await fn(items[idx]);
      }
    }),
  );
  return out;
}

export async function analyzeRepo(input: string, token: string | null): Promise<Analysis> {
  const { owner, repo } = await resolveRepo(input, token);

  const [meta, codeFreq, commitAct, languagesRaw, contribStats, recentCommitsList] =
    await Promise.all([
      ghJson(`${GH}/repos/${owner}/${repo}`, token),
      ghJson(`${GH}/repos/${owner}/${repo}/stats/code_frequency`, token),
      ghJson(`${GH}/repos/${owner}/${repo}/stats/commit_activity`, token),
      ghJson(`${GH}/repos/${owner}/${repo}/languages`, token),
      ghJson(`${GH}/repos/${owner}/${repo}/stats/contributors`, token).catch(() => []),
      ghJson(`${GH}/repos/${owner}/${repo}/commits?per_page=30`, token),
    ]);

  // Weekly series
  const commitByWeek = new Map<number, number>();
  for (const w of commitAct ?? []) commitByWeek.set(w.week, w.total);

  let cumulative = 0;
  const baseSeries = (codeFreq ?? []).map((row: number[], i: number) => {
    const [week, additions, deletions] = row;
    const net = additions + deletions; // deletions negative
    cumulative += net;
    const d = new Date(week * 1000);
    return {
      weekIdx: i,
      date: d.toISOString().slice(0, 10),
      label: `${d.toLocaleString("en", { month: "short" })} '${String(d.getFullYear()).slice(2)}`,
      additions,
      deletions: -deletions,
      net,
      cumulative,
      commits: commitByWeek.get(week) ?? 0,
    };
  });
  const series: WeekPoint[] = baseSeries.map((p: any, i: number, arr: any[]) => {
    const win = arr.slice(Math.max(0, i - 3), i + 1);
    const velocity = Math.round(win.reduce((s, x) => s + x.additions, 0) / win.length);
    return { ...p, velocity };
  });

  const totalAdditionsYear = series.slice(-52).reduce((s, p) => s + p.additions, 0);
  const totalDeletionsYear = series.slice(-52).reduce((s, p) => s + p.deletions, 0);
  const totalCommitsYear = series.slice(-52).reduce((s, p) => s + p.commits, 0);
  const netLocYear = totalAdditionsYear - totalDeletionsYear;

  const last4 = series.slice(-4).reduce((s, p) => s + p.commits, 0);
  const prev4 = series.slice(-8, -4).reduce((s, p) => s + p.commits, 0);
  const monthlyCommitChange =
    prev4 === 0 ? (last4 > 0 ? 100 : 0) : Math.round(((last4 - prev4) / prev4) * 100);

  const avgDailyLoc = Math.round(totalAdditionsYear / (52 * 7) || 0);
  const largestWeek = series.length
    ? series.reduce((a, b) => (b.additions > a.additions ? b : a), series[0])
    : null;

  // Languages
  const totalBytes = Object.values(languagesRaw || {}).reduce(
    (s: number, v: any) => s + (v as number),
    0,
  );
  const languages: LanguageSlice[] = Object.entries(languagesRaw || {})
    .map(([name, bytes]) => ({
      name,
      bytes: bytes as number,
      pct: totalBytes ? ((bytes as number) / totalBytes) * 100 : 0,
    }))
    .sort((a, b) => b.bytes - a.bytes)
    .slice(0, 6);

  // Contributors (top 5)
  const contributors: Contributor[] = (Array.isArray(contribStats) ? contribStats : [])
    .sort((a: any, b: any) => b.total - a.total)
    .slice(0, 5)
    .map((c: any) => {
      const additions = (c.weeks ?? []).reduce((s: number, w: any) => s + (w.a ?? 0), 0);
      const deletions = (c.weeks ?? []).reduce((s: number, w: any) => s + (w.d ?? 0), 0);
      return {
        login: c.author?.login ?? "unknown",
        avatar: c.author?.avatar_url ?? "",
        commits: c.total,
        additions,
        deletions,
      };
    });

  // Per-commit stats (fetch in parallel for the recent slice)
  const commitDetails = await pool(recentCommitsList.slice(0, 30), 5, async (c: any) => {
    try {
      return await ghJson(`${GH}/repos/${owner}/${repo}/commits/${c.sha}`, token);
    } catch {
      return null;
    }
  });

  const recentCommits: CommitRow[] = commitDetails.filter(Boolean).map((c: any): CommitRow => {
    const additions = c.stats?.additions ?? 0;
    const deletions = c.stats?.deletions ?? 0;
    const total = c.stats?.total ?? additions + deletions;
    const files = c.files?.length ?? 0;
    const message: string = c.commit?.message ?? "";
    const firstLine = message.split("\n")[0] ?? "";
    const aiSignals = detectAiSignals(message, additions, files);
    return {
      sha: c.sha,
      shortSha: c.sha.slice(0, 7),
      author: c.commit?.author?.name ?? "unknown",
      authorLogin: c.author?.login ?? null,
      avatar: c.author?.avatar_url ?? null,
      date: c.commit?.author?.date ?? "",
      message,
      firstLine,
      additions,
      deletions,
      total,
      files,
      aiSignals,
      url: c.html_url,
    };
  });

  const addsArr = recentCommits.map((c) => c.additions);
  const avgLocPerCommit = addsArr.length
    ? Math.round(addsArr.reduce((s, x) => s + x, 0) / addsArr.length)
    : 0;
  const medianLocPerCommit = median(addsArr);

  // Improved AI score
  const aiCommits = recentCommits.filter((c) => c.aiSignals.length > 0).length;
  const aiRatio = recentCommits.length ? aiCommits / recentCommits.length : 0;
  const burstRatio = recentCommits.length
    ? recentCommits.filter((c) => c.additions > 1000 && c.files >= 4).length / recentCommits.length
    : 0;
  const sizeFactor = Math.min(avgLocPerCommit / 6, 35); // up to 35 pts
  const skewFactor = Math.min((avgLocPerCommit - medianLocPerCommit) / 10, 20); // batchy commits

  const breakdown = [
    { label: "Avg LOC per commit", value: Math.round(sizeFactor), weight: 35 },
    {
      label: "Median vs avg skew",
      value: Math.max(0, Math.round(skewFactor)),
      weight: 20,
    },
    { label: "Large multi-file commits", value: Math.round(burstRatio * 25), weight: 25 },
    {
      label: "AI keywords in messages",
      value: Math.round(aiRatio * 20),
      weight: 20,
    },
  ];
  let aiScore = breakdown.reduce((s, b) => s + b.value, 0);
  if (recentCommits.length < 5) aiScore = 0;
  aiScore = Math.max(0, Math.min(100, aiScore));

  const aiReason =
    aiScore >= 70
      ? "Strong signals: large batch commits, AI keywords, or skewed sizes."
      : aiScore >= 45
        ? "Mixed signals — some commits look AI-assisted."
        : "Patterns consistent with hand-written, iterative development.";

  return {
    owner,
    repo,
    fullName: `${owner}/${repo}`,
    url: meta.html_url,
    description: meta.description,
    stars: meta.stargazers_count,
    forks: meta.forks_count,
    openIssues: meta.open_issues_count,
    watchers: meta.subscribers_count ?? meta.watchers_count,
    defaultBranch: meta.default_branch,
    createdAt: meta.created_at,
    updatedAt: meta.pushed_at,
    primaryLanguage: meta.language,
    series,
    totalCommitsYear,
    totalAdditionsYear,
    totalDeletionsYear,
    netLocYear,
    avgDailyLoc,
    monthlyCommitChange,
    largestWeek,
    languages,
    contributors,
    recentCommits,
    commitsAnalyzed: recentCommits.length,
    avgLocPerCommit,
    medianLocPerCommit,
    aiScore,
    aiBreakdown: breakdown,
    aiReason,
  };
}

export function formatCompact(n: number): string {
  const abs = Math.abs(n);
  if (abs >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (abs >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
  return `${n}`;
}

// ─── Persistent local storage ──────────────────────────────────────────
// Data is namespaced per connected GitHub account (or "anon" when signed
// out), so each user who connects keeps their own history and tracked
// repos across sessions on the same browser.

const TOKEN_KEY = "gitfiles:token";
const VIEWER_KEY = "gitfiles:viewer";

export type HistoryItem = { fullName: string; analyzedAt: number };

export type TrackedSnapshot = {
  at: number;
  netLocYear: number;
  totalCommitsYear: number;
  aiScore: number;
  stars: number;
};

export type TrackedRepo = {
  fullName: string;
  trackedAt: number;
  snapshots: TrackedSnapshot[];
};

function ns(): string {
  return loadViewer()?.login ?? "anon";
}
function readJson<T>(key: string, fallback: T): T {
  if (typeof window === "undefined") return fallback;
  try {
    const raw = localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch {
    return fallback;
  }
}
function writeJson(key: string, value: unknown) {
  if (typeof window !== "undefined") localStorage.setItem(key, JSON.stringify(value));
}

// Token + viewer profile -------------------------------------------------
export function loadToken(): string {
  if (typeof window === "undefined") return "";
  return localStorage.getItem(TOKEN_KEY) ?? "";
}
export function saveToken(t: string) {
  if (typeof window === "undefined") return;
  if (t) localStorage.setItem(TOKEN_KEY, t);
  else localStorage.removeItem(TOKEN_KEY);
}
export function loadViewer(): Viewer | null {
  return readJson<Viewer | null>(VIEWER_KEY, null);
}
export function saveViewer(v: Viewer | null) {
  if (typeof window === "undefined") return;
  if (v) writeJson(VIEWER_KEY, v);
  else localStorage.removeItem(VIEWER_KEY);
}

// Recent-analysis history ------------------------------------------------
export function loadHistory(): HistoryItem[] {
  return readJson<HistoryItem[]>(`gitfiles:${ns()}:history`, []);
}
export function pushHistory(fullName: string) {
  const cur = loadHistory().filter((h) => h.fullName !== fullName);
  cur.unshift({ fullName, analyzedAt: Date.now() });
  writeJson(`gitfiles:${ns()}:history`, cur.slice(0, 8));
}
export function clearHistory() {
  if (typeof window !== "undefined") localStorage.removeItem(`gitfiles:${ns()}:history`);
}

// Tracked repos with snapshot timelines -----------------------------------
export function loadTracked(): TrackedRepo[] {
  return readJson<TrackedRepo[]>(`gitfiles:${ns()}:tracked`, []);
}
export function isTracked(fullName: string): boolean {
  return loadTracked().some((t) => t.fullName === fullName);
}
export function trackRepo(a: Analysis): TrackedRepo[] {
  const all = loadTracked();
  if (!all.some((t) => t.fullName === a.fullName)) {
    all.unshift({ fullName: a.fullName, trackedAt: Date.now(), snapshots: [] });
  }
  const next = recordSnapshot(all, a);
  writeJson(`gitfiles:${ns()}:tracked`, next.slice(0, 20));
  return next;
}
export function untrackRepo(fullName: string): TrackedRepo[] {
  const next = loadTracked().filter((t) => t.fullName !== fullName);
  writeJson(`gitfiles:${ns()}:tracked`, next);
  return next;
}
/** Append a snapshot to a tracked repo whenever it is re-analyzed. */
export function maybeSnapshot(a: Analysis): TrackedRepo[] {
  const all = loadTracked();
  if (!all.some((t) => t.fullName === a.fullName)) return all;
  const next = recordSnapshot(all, a);
  writeJson(`gitfiles:${ns()}:tracked`, next);
  return next;
}
function recordSnapshot(all: TrackedRepo[], a: Analysis): TrackedRepo[] {
  return all.map((t) => {
    if (t.fullName !== a.fullName) return t;
    const snap: TrackedSnapshot = {
      at: Date.now(),
      netLocYear: a.netLocYear,
      totalCommitsYear: a.totalCommitsYear,
      aiScore: a.aiScore,
      stars: a.stars,
    };
    const last = t.snapshots[t.snapshots.length - 1];
    // Collapse snapshots taken within the same hour to avoid noise.
    const snapshots =
      last && Date.now() - last.at < 60 * 60 * 1000
        ? [...t.snapshots.slice(0, -1), snap]
        : [...t.snapshots, snap];
    return { ...t, snapshots: snapshots.slice(-60) };
  });
}
